CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id),
    type TEXT NOT NULL CHECK (type IN (
        'TICKET_INSPECTION',
        'VEHICLE_STOPPED',
        'VEHICLE_BREAKDOWN',
        'ROUTE_BLOCKED',
        'STOP_CLOSED',
        'DELAY',
        'OTHER'
    )),
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED')),
    line_number TEXT,
    stop_name TEXT,
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    verified_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_reports_author_id ON reports(author_id);
CREATE INDEX idx_reports_status_created_at ON reports(status, created_at DESC);
