CREATE TABLE report_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_report_confirmations_report_user UNIQUE (report_id, user_id)
);

CREATE INDEX idx_report_confirmations_report_id ON report_confirmations(report_id);
CREATE INDEX idx_report_confirmations_user_id ON report_confirmations(user_id);
